# 座標回帰用 LightningModule設定
name: coord_regression
_target_: src.ball.lit_module.coord_regression_lit_module.CoordRegressionModule

# モデルは外部で定義されたものを参照
model: ${model}

# 学習パラメータ
lr: 1e-3
weight_decay: 1e-4
freeze_backbone_epochs: 0 