# 座標回帰用 LightningModule設定
module:
  _target_: src.ball.lit_module.coord_regression_lit_module.CoordRegressionLitModule
  # 学習パラメータ
  lr: 1e-3
  weight_decay: 1e-4
  freeze_backbone_epochs: 0 

meta:
  name: coord_regression
  output_type: "coord"
