# 自己学習座標回帰用 LightningModule設定
module:
  _target_: src.ball.lit_module.self_training_lit_module.SelfTrainingCoordLitModule

  # 学習パラメータ
  lr: 1e-3
  weight_decay: 1e-4
  warmup_epochs: 1
  max_epochs: ${trainer.max_epochs}
  pseudo_weight: 0.5  # 擬似ラベルの重み

meta:
  name: self_training_coord
  output_type: "coord" 