# configs/module/seq_lite_transformer_focal.yaml

# VideoSwinTransformer用LightningModule設定 (Focal Loss版)
module:
  _target_: src.ball.lit_module.lit_seq_lite_transformer_focal.LitSeqLiteTransformerFocalLoss

  # モデル構成パラメータ
  img_size: [320, 640]  # データセットに合わせて調整
  in_channels: 3
  out_channels: 1
  n_frames: ${litdatamodule.T}
  window_size: 5
  feature_dim: 256
  transformer_blocks: 4
  transformer_heads: 8
  
  # 学習パラメータ
  lr: 1e-4
  weight_decay: 1e-5
  warmup_epochs: 1
  max_epochs: ${trainer.max_epochs}
  
  # Focal Loss用パラメータ
  focal_alpha: 0.25
  focal_gamma: 2.0

  # 可視化パラメータ
  num_log_images: 4

meta:
  name: "seq_lite_transformer_focal"
  output_type: "heatmap_sequence"