# VideoSwinTransformer軽量版 LightningModule設定
module:
  _target_: src.ball.lit_module.lit_seq_lite_transformer.LitSeqLiteTransformer

  # モデル構成パラメータ（軽量化）
  img_size: [320, 640]
  in_channels: 3
  out_channels: 1
  n_frames: ${litdatamodule.T}
  window_size: 5        # 小さいウィンドウ
  feature_dim: 128      # 特徴次元を半分に
  transformer_blocks: 1 # ブロック数を減らす
  transformer_heads: 4  # ヘッド数を半分に

  # 学習パラメータ
  lr: 1e-4
  weight_decay: 1e-4
  warmup_epochs: 1
  max_epochs: ${trainer.max_epochs}
  bce_weight: 0.7
  # 可視化パラメータ
  num_log_images: 2

meta:
  name: seq_lite_transformer_small
  output_type: "heatmap_sequence"
  description: "Lightweight VideoSwinTransformer for testing and resource-constrained environments" 