# Swin用 LightningModule設定
module:
  _target_: src.ball.lit_module.lit_swin.LitSwin

  # モデル構成パラメータ
  in_channels: ${litdatamodule.T}
  out_channels: 1
  final_channels: [64, 32]
  swin_model: "swin_base_patch4_window7_224"
  pretrained: true
  img_size: 448

  # 学習パラメータ
  lr: 1e-3
  weight_decay: 1e-4
  warmup_epochs: 1
  max_epochs: ${trainer.max_epochs}
  bce_weight: 0.7

meta:
  name: swin
  output_type: "heatmap" 