# デフォルトキューシステム設定
# 標準的なストリーミング処理用の基本設定

# 基本キューサイズ設定
base_queue_sizes:
  preprocess: 16
  inference: 16  
  postprocess: 16
  results: 100

# ワーカー別拡張キュー設定
worker_extended_queues:
  ball:
    ball_inference: 32
  
  court:
    court_inference: 32
  
  pose:
    detection_inference: 32
    detection_postprocess: 32
    pose_inference: 32
    pose_postprocess: 32

# キュータイプ設定
queue_types:
  preprocess: "Queue"
  inference: "Queue"
  postprocess: "Queue"
  results: "PriorityQueue"
  detection_inference: "Queue"
  detection_postprocess: "Queue"
  pose_inference: "Queue"
  pose_postprocess: "Queue"
  ball_inference: "Queue"
  court_inference: "Queue"

# パフォーマンス設定
performance:
  enable_monitoring: true
  log_queue_status: false
  auto_clear_on_shutdown: true 