# 軽量キューシステム設定
# メモリ使用量を最小限に抑えた設定

defaults:
  - default

# 軽量キューサイズ設定（小容量）
base_queue_sizes:
  preprocess: 8
  inference: 8
  postprocess: 8
  results: 32

# ワーカー別拡張キュー設定（軽量）
worker_extended_queues:
  ball:
    ball_inference: 16
  
  court:
    court_inference: 16
  
  pose:
    detection_inference: 16
    detection_postprocess: 8
    pose_inference: 16
    pose_postprocess: 8

# 標準キュータイプ（軽量化）
queue_types:
  preprocess: "Queue"
  inference: "Queue"
  postprocess: "Queue"
  results: "Queue"  # PriorityQueueよりも軽量
  detection_inference: "Queue"
  detection_postprocess: "Queue"
  pose_inference: "Queue"
  pose_postprocess: "Queue"
  ball_inference: "Queue"
  court_inference: "Queue"

# 軽量設定
performance:
  enable_monitoring: false  # 監視機能オフ
  log_queue_status: false
  auto_clear_on_shutdown: true
  memory_optimization: true
  minimal_threads: true 