# @package _global_

# hydra設定
hydra:
  output_subdir: hydra_outputs/${now:%Y-%m-%d_%H-%M-%S}
  run:
    dir: .

# デフォルト設定
defaults:
  # LightningModuleの選択
  # コマンドライン例: litmodule=rtdetr
  - litmodule: rtdetr
  
  - litdatamodule: coco_data
  - trainer: default
  - callbacks: default
  - _self_

# 実験名（ディレクトリ名）の設定
version: ${litmodule.meta.name}_player_detection

# 再現性のための乱数シード
seed: 42 