# @package _global_

# hydra設定
hydra:
  output_subdir: hydra_outputs/${now:%Y-%m-%d_%H-%M-%S}
  run:
    dir: .

# デフォルト設定
defaults:
  # Model configuration
  - model: rtdetr
  
  # LightningModule configuration
  - litmodule: generic_detection
  
  - litdatamodule: coco_data
  - trainer: default
  - callbacks: default
  - _self_

# 実験名（ディレクトリ名）の設定
version: ${model.meta.name}_${litmodule.meta.name}_player_detection

# 再現性のための乱数シード
seed: 42