# @package _global_

# This is the main configuration file for a specific experiment.
# It composes different components (model, lit_module, datamodule, etc.)

defaults:
  - override /model: lite_tracknet
  - override /litmodule: generic_focal_loss
  - override /litdatamodule: 3_frames_cat_last
  - override /trainer: default
  - override /callbacks: default
  - _self_

# Inject the instantiated 'model' into the 'litmodule' configuration.
# This is where the dependency injection happens.
litmodule:
  model: ${model}
