# @package _global_

# hydra設定
hydra:
  output_subdir: hydra_outputs/${now:%Y-%m-%d_%H-%M-%S}
  run:
    dir: .

# デフォルト設定
defaults:
  # モデルアーキテクチャの選択（cat_frames, single_frame, sequence）
  # コマンドライン例: model=_cat_frames model@model.cat_frames=lite_tracknet_xy
  - model: _cat_frames
  
  # LightningModuleの選択（自己学習用）
  - litmodule: self_training_heatmap
  
  # 自己学習用データモジュール
  - litdatamodule: self_training_ball_data
  
  - trainer: default
  - callbacks: default
  - _self_

# 自己学習パラメータ
self_training:
  max_cycles: 3
  confidence_threshold: 0.7
  trajectory_window: 9
  max_trajectory_gap: 5
  min_trajectory_length: 7

# 実験名（ディレクトリ名）の設定
# モデル名とデータセットタイプから自動生成
version: self_training_${model.meta.name}_${litdatamodule.dataset_type}

# 再現性のための乱数シード
seed: 42 