# @package _global_

# hydra設定
hydra:
  output_subdir: hydra_outputs/${now:%Y-%m-%d_%H-%M-%S}
  run:
    dir: outputs/ball/${litmodule.meta.name}/${now:%Y-%m-%d_%H-%M-%S}

# デフォルト設定
defaults:
  - litmodule: seq_lite_transformer_focal
  - litdatamodule: seq_transformer
  - trainer: default
  - callbacks: default
  - _self_

# 再現性のための乱数シード
seed: 42

# 実験名の設定
version: ${litmodule.meta.name}_${litdatamodule.dataset_type} 