# @package _global_

# VideoSwinTransformer軽量版トレーニング設定

# hydra設定
hydra:
  output_subdir: hydra_outputs/${now:%Y-%m-%d_%H-%M-%S}
  run:
    dir: outputs/ball/${litmodule.meta.name}/${now:%Y-%m-%d_%H-%M-%S}

# デフォルト設定
defaults:
  - litmodule: seq_lite_transformer_small
  - litdatamodule: seq_transformer_small
  - trainer: default
  - callbacks: default
  - _self_

# 再現性のための乱数シード
seed: 42

# 実験名の設定
version: ${litmodule.meta.name}_${litdatamodule.T}frames_${litdatamodule.dataset_type}

# 追加設定
experiment:
  name: "VideoSwinTransformer Small Ball Tracking"
  description: "Training lightweight VideoSwinTransformer for tennis ball tracking (testing/development)"
  tags: ["transformer", "swin", "sequence", "ball_tracking", "lightweight"] 