# @package _global_.litmodule

module:
  _target_: src.court.lit_module.lit_fpn.LitFpn
  
  # モデル構成パラメータ
  in_channels: 3
  base_ch: 64
  out_channels: 15
  
  # 学習パラメータ
  lr: 0.001
  weight_decay: 0.0001
  warmup_epochs: 1
  max_epochs: 50
  bce_weight: 0.7

# メタ情報
meta:
  name: fpn
  output_type: "heatmap" 