# @package _global_.litmodule

module:
  _target_: src.court.lit_module.lit_generic_court_model.LitGenericCourtModel
  model: ${model}
  
  # Loss function configuration
  criterion:
    alpha: 1.0
    gamma: 2.0
    reduction: "mean"
  
  # Optimizer configuration
  optimizer_params:
    class: "AdamW"
    lr: 0.0001
    weight_decay: 0.0001
    betas: [0.9, 0.999]
  
  # Scheduler configuration
  scheduler_params:
    scheduler: "cosine_with_warmup"
    warmup_epochs: 1
    max_epochs: 50
    eta_min_factor: 0.01
  
  # Evaluation parameters
  accuracy_threshold: 5.0
  num_log_images: 4
  
  # Data format parameters
  use_peak_valley_heatmaps: true

# Meta information
meta:
  name: generic_focal
  loss_type: "focal_loss"