# LiteTrackNetモデル設定
net:
  _target_: src.ball.models.lite_tracknet.LiteTrackNet

  # モデル構成パラメータ
  in_channels: ${litdatamodule.T}
  out_channels: 1

# メタ情報をまとめる
meta:
  name: lite_tracknet
  output_type: "heatmap"
