# @package _group_

_target_: src.ball.models.video_swin_transformer.VideoSwinTransformer

# Parameters for the VideoSwinTransformer model
img_size: [320, 640]
in_channels: 3
out_channels: 1
n_frames: 10
window_size: 7
feature_dim: 256
transformer_blocks: 2
transformer_heads: 8
