_target_: transformers.ConditionalDetrImageProcessor.from_pretrained
pretrained_model_name_or_path: microsoft/conditional-detr-resnet-50
use_fast: True
size: {"shortest_edge": ${data.shortest_edge}, "longest_edge": ${data.longest_edge}}