# @package _global_.model

# LiteTrackNet XY（座標回帰版）モデル設定
net:
  _target_: src.ball.models.cat_frames.lite_tracknet_xy.LiteTrackNetXY

  # モデル構成パラメータ
  in_channels: ${litdatamodule.T}

# メタ情報をまとめる
meta:
  name: lite_tracknet_xy
  output_type: "coord" 