# @package _global_.model

# オリジナルTrackNetモデル設定
net:
  _target_: src.ball.models.cat_frames.tracknet.BallTrackerNet

  # モデル構成パラメータ
  in_channels: ${litdatamodule.T}
  out_channels: 1
# メタ情報をまとめる
meta:
  name: tracknet
  output_type: "heatmap" 