# Xceptionモデル設定
name: xception
_target_: src.ball.models.cat_frames.xception.XceptionHeatmapNet

# モデル構成パラメータ
in_channels: ${litdatamodule.T}
base_channels: 32
out_channels: 1
num_xceptions: [1, 1, 2, 2, 1, 1] 