# @package _global_

# hydra設定
hydra:
  output_subdir: hydra_outputs/${now:%Y-%m-%d_%H-%M-%S}
  run:
    dir: .

# デフォルト設定
defaults:
  # モデルアーキテクチャの選択
  # コマンドライン例: model=fpn
  - model: fpn
  
  # LightningModuleの選択
  # コマンドライン例: litmodule=heatmap_regression
  - litmodule: heatmap_regression
  
  - litdatamodule: court_data
  - trainer: default
  - callbacks: default
  - _self_

# 実験名（ディレクトリ名）の設定
# モデル名とデータセットタイプから自動生成
version: ${model.name}_court_keypoints

# 再現性のための乱数シード
seed: 42 