# @package _global_

defaults:
  - config
  - _self_

# チェックポイントパス
checkpoint_path: "models/checkpoints/court/best.ckpt"

# 予測設定
predict:
  # 単一画像の予測
  image_path: null  # 指定する場合はパスを設定
  
  # ディレクトリ内の画像をバッチ処理
  image_dir: "datasets/test"  # テスト画像のディレクトリ
  
  # 出力設定
  output_dir: "outputs/court"
  threshold: 0.5  # ヒートマップの閾値
  visualize_mode: "overlay"  # "overlay" または "heatmap" 