# @package _group_
_target_: pytorch_lightning.Trainer

accelerator: "auto" # Options: "cpu", "gpu", "tpu", "ipu", "hpu", "mps", "auto"
devices: "auto" # Number of devices to train on (e.g., 1, [0, 1], "auto")
max_epochs: 100
precision: "32-true" # Options: "16-mixed", "bf16-mixed", "32-true", "64-true"
log_every_n_steps: 50

# Other common Trainer flags:
# deterministic: false # For reproducibility, can impact performance
# enable_progress_bar: true
# gradient_clip_val: 0.5 # Example gradient clipping
# accumulate_grad_batches: 1 # Number of batches to accumulate gradients over

# For more options, see Pytorch Lightning Trainer documentation
