# @package _global_.model

# MobileTransモデル設定
net:
  _target_: src.ball.models.sequence.mobile_trans.CNNTemporalKeypointModel

  # モデル構成パラメータ
  num_keypoints: 1
  hidden_dim: 128
  num_heads: 4
  num_layers: 2

# メタ情報をまとめる
meta:
  name: mobile_trans
  output_type: "coord" 