# @package _global_.model

# TimeSformerモデル設定
net:
  _target_: src.ball.models.sequence.TSformer_ball.TimeSformerBall

  # モデル構成パラメータ
  num_keypoints: 1
  pretrained_model: "facebook/timesformer-base-finetuned-k400"

# メタ情報をまとめる
meta:
  name: tsformer_ball
  output_type: "heatmap" 