# @package _global_.model

# UNet3Dモデル設定
net:
  _target_: src.ball.models.sequence.UNet_3D.UNet3D

  # モデル構成パラメータ
  in_ch: 3
  base_ch: 32
  t_frames: ${litdatamodule.T}
  num_keypoints: 1

# メタ情報をまとめる
meta:
  name: unet_3d
  output_type: "heatmap" 