_target_: src.court.models.fpn.CourtDetectorFPN
in_channels: 3 # Default
base_ch: 64 # Default
out_channels: 15 # 15 keypoints for court
ckpt_path: "checkpoints/court/fpn/court-epoch=02-val_loss=0.0033.ckpt"