# @package _global_.model

# FPNモデル設定
net:
  _target_: src.court.models.fpn.CourtDetectorFPN

  # モデルパラメータ
  in_channels: 3
  base_ch: 64
  out_channels: 15

# メタ情報をまとめる
meta:
  name: fpn
  output_type: "heatmap" 