# @package _global_.model

# SwinCourtUNet モデル設定
net:
  _target_: src.court.models.swin_court.SwinCourtUNet

  # モデルパラメータ
  out_channels: 15
  final_channels: [64, 32]
  swin_model: "swin_base_patch4_window7_224"
  pretrained: true

# メタ情報をまとめる
meta:
  name: swin_court
  output_type: "heatmap" 