# Swin 384モデル設定
name: swin_384_court
_target_: src.court.models.swin_384_court.SwinCourtUNet

# モデルパラメータ
num_keypoints: 15
final_channels: [64, 32]
swin_model: "swin_base_patch4_window7_224"
pretrained: true
img_size: 384 