# @package visualization

# 可視化設定
ball_radius: 8  # ボール描画半径
trajectory_length: 20  # 軌跡表示フレーム数
enable_smoothing: false  # 位置スムージング有効化
enable_prediction: false  # 位置予測表示有効化
confidence_threshold: 0.5  # 信頼度閾値 