# Self-Training用コールバック設定
model_checkpoint:
  _target_: pytorch_lightning.callbacks.ModelCheckpoint
  dirpath: ${self_training.save_dir}/checkpoints
  filename: "{epoch:03d}-{val_loss:.4f}"
  monitor: "val_loss"
  mode: "min"
  save_top_k: 3
  save_last: true
  save_weights_only: false
  auto_insert_metric_name: false
  verbose: true

learning_rate_monitor:
  _target_: pytorch_lightning.callbacks.LearningRateMonitor
  logging_interval: "step"

rich_progress_bar:
  _target_: pytorch_lightning.callbacks.RichProgressBar
  refresh_rate: 10

model_summary:
  _target_: pytorch_lightning.callbacks.RichModelSummary
  max_depth: 2

# Self-trainingでは早期終了は使用しない（サイクル単位で制御）
# early_stopping:
#   _target_: pytorch_lightning.callbacks.EarlyStopping
#   monitor: "val_loss"
#   patience: 10
#   mode: "min"
#   min_delta: 0.0001
#   verbose: true 