# Flexible Tennis Analysis Pipeline Configuration

# Device configuration
device: auto  # auto, cuda, cpu

# Batch processing
batch_size: 32

# Buffer settings
buffer_size: 100

# Threading configuration
threading:
  mode: single  # single, multi
  queue_size: 50
  workers:
    video_input: 1
    preprocessing: 2
    inference: 1
    postprocessing: 2
    video_output: 1

# I/O configuration
io:
  input_video: datasets/test/video_input2.mp4  # Required: path to input video
  output_video: demo_output_integrated.mp4  # Optional: path to output video
  output_csv: analysis_results.csv  # Optional: path to CSV results file
  codec: mp4v

# Logging configuration
logging:
  level: INFO
  format: "%(asctime)s - %(levelname)s - %(name)s - %(message)s"

# Visualization configuration
visualization:
  enabled: true
  court:
    keypoint_color: [0, 255, 0]
    keypoint_radius: 3
    skeleton_color: [255, 0, 0]
    skeleton_thickness: 2
    score_threshold: 0.5
  ball:
    color: [0, 0, 255]
    radius: 8
    show_score: true
  player:
    bbox_color: [255, 255, 0]
    bbox_thickness: 2
    show_score: true
  pose:
    keypoint_color: [0, 255, 255]
    keypoint_radius: 3
    skeleton_color: [255, 0, 255]
    skeleton_thickness: 2
    score_threshold: 0.3

# Task configuration
tasks:
  - name: court_detection
    module: src.integrate.tasks.court_task
    class_name: CourtDetectionTask
    enabled: true
    critical: true
    dependencies: []
    config:
      checkpoint: checkpoints/court/lit_vit_unet/best_model.ckpt
      input_size: [224, 224]
      score_threshold: 0.5
      multi_channel: true

  - name: ball_tracking
    module: src.integrate.tasks.ball_task
    class_name: BallTrackingTask
    enabled: true
    critical: false
    dependencies: []
    config:
      model_path: checkpoints/ball/hrnet/wasb_tennis_best.pth.tar
      score_threshold: 0.3
      tracking_enabled: false

  - name: player_detection
    module: src.integrate.tasks.player_task
    class_name: PlayerDetectionTask
    enabled: true
    critical: false
    dependencies: []
    config:
      checkpoint: checkpoints/player/lit_rt_detr/best_model.ckpt
      confidence_threshold: 0.5

  - name: pose_estimation
    module: src.integrate.tasks.pose_task
    class_name: PoseEstimationTask
    enabled: true
    critical: false
    dependencies: [player_detection]
    config:
      model_name: "usyd-community/vitpose-base-simple"
      keypoint_threshold: 0.3

# Performance monitoring
performance:
  enable_profiling: false
  log_timing: true
  memory_monitoring: false

# Error handling
error_handling:
  continue_on_task_failure: true
  max_retries: 3
  retry_delay: 1.0

defaults:
  - _self_