# EventDetectionLitModule model configuration
_target_: src.event.lit_module.event_detection_lit_module.EventDetectionLitModule
d_model: 128
nhead: 8
num_layers: 4
dropout: 0.1
max_seq_len: 512
pose_dim: 51

# チェックポイントパス
ckpt_path: "checkpoints/event/transformer_v2/latest.ckpt" 