# EventTransformer model configuration
_target_: src.event.models.transformer.EventTransformer
d_model: 128
nhead: 8
num_layers: 4
dropout: 0.1
max_seq_len: 512
pose_dim: 51

# チェックポイントパス
ckpt_path: "checkpoints/event/transformer/epoch=12-step=3809.ckpt" 