# @package _global_.model

# MobileNetモデル設定
net:
  _target_: src.ball.models.single_frame.mobilenet.MobileNetV3Ball

  # モデル構成パラメータ
  num_classes: 1
  pretrained: true

# メタ情報をまとめる
meta:
  name: mobilenet
  output_type: "coord" 