# VideoSwinTransformer用データモジュール設定
_target_: src.ball.lit_datamodule.ball_data_module.TennisBallDataModule

# データパス
annotation_file: 'datasets/ball/coco_annotations_ball_pose_court.json'
image_root: 'datasets/ball/images'

# 入力設定 - シーケンス用
T: 16  # VideoSwinTransformerで扱いやすいフレーム数
batch_size: 2  # Transformerは大きなメモリを使うため小さめ
num_workers: 4
skip_frames_range: [1, 3]  # より密なサンプリング
input_type: "stack"      # フレームを独立して扱う
output_type: "all"       # 全フレームのヒートマップを出力
dataset_type: "heatmap"  # ヒートマップベース

# 画像サイズ設定 - VideoSwinTransformerに合わせて調整
input_size: [320, 640]   # Transformerで処理しやすいサイズ
heatmap_size: [320, 640]

# 変換設定
train_transform:
  _target_: src.ball.arguments.prepare_transform.prepare_transform
  input_size: ${litdatamodule.input_size}
  is_train: true

val_test_transform:
  _target_: src.ball.arguments.prepare_transform.prepare_transform
  input_size: ${litdatamodule.input_size}
  is_train: false
