# コート検出用データモジュール設定
_target_: src.court.lit_datamodule.court_datamodule.CourtDataModule

# データパス
annotation_root: 'datasets/court/'
image_root: 'datasets/court/images'

# データローダー設定
batch_size: 16
num_workers: 8

# 画像サイズ設定
input_size: [360, 640]
heatmap_size: [360, 640]

# ヒートマップ設定
default_keypoints: 15
is_each_keypoint: false
sigma: 3.0

# 変換設定
train_transform:
  _target_: src.court.arguments.prepare_transform.prepare_transform
  input_size: ${litdatamodule.input_size}
  is_train: true

val_test_transform:
  _target_: src.court.arguments.prepare_transform.prepare_transform
  input_size: ${litdatamodule.input_size}
  is_train: false 