# @package _group_
_target_: src.court.lit_datamodule.datamodule.CourtLitDataModule

data_root: "path/to/your/court_dataset_root/" # TODO: User needs to set this path
train_annotations: "${data_root}/train_annotations.json" # Example path
val_annotations: "${data_root}/val_annotations.json"     # Example path
test_annotations: "${data_root}/test_annotations.json"    # Example path (optional)

batch_size: 8
num_workers: 4
input_size: [384, 384] # Example input size (height, width), adjust as per model requirements

# Augmentation settings (placeholders, to be defined in the LitDataModule or here)
augmentations:
  train:
    # - type: RandomResizedCrop
    #   height: ${..input_size[0]}
    #   width: ${..input_size[1]}
    #   scale: [0.8, 1.0]
    # - type: HorizontalFlip
    #   p: 0.5
    # - type: ColorJitter
    #   brightness: 0.2
    #   contrast: 0.2
    #   saturation: 0.2
    #   hue: 0.1
    # - type: Normalize
    #   mean: [0.485, 0.456, 0.406]
    #   std: [0.229, 0.224, 0.225]
    pass # No augmentations defined by default, add as needed

  val:
    # - type: Resize
    #   height: ${..input_size[0]}
    #   width: ${..input_size[1]}
    # - type: Normalize
    #   mean: [0.485, 0.456, 0.406]
    #   std: [0.229, 0.224, 0.225]
    pass # No augmentations defined by default, add as needed

  test:
    # - type: Resize
    #   height: ${..input_size[0]}
    #   width: ${..input_size[1]}
    # - type: Normalize
    #   mean: [0.485, 0.456, 0.406]
    #   std: [0.229, 0.224, 0.225]
    pass # No augmentations defined by default, add as needed
