# 自己学習用コート検出データモジュール設定
_target_: src.court.lit_datamodule.self_training_court_datamodule.SelfTrainingCourtDataModule

# ラベル付きデータパス
annotation_root: 'datasets/court/annotations'
image_root: 'datasets/court/images'

# 未ラベルデータパス
unlabeled_annotation_file: 'datasets/court/unlabeled/coco_annotations_unlabeled.json'
unlabeled_image_root: 'datasets/court/unlabeled/images'

# 擬似ラベル設定
pseudo_label_dir: 'outputs/court/self_training/pseudo_labels'
pseudo_label_weight: 0.5

# データローダー設定
batch_size: 8
num_workers: 8

# 画像サイズ設定
input_size: [224, 224]
heatmap_size: [224, 224]

# ヒートマップ設定
default_keypoints: 15
is_each_keypoint: false
sigma: 2.0

# 変換設定
train_transform:
  _target_: src.court.arguments.prepare_transform.prepare_transform
  input_size: ${litdatamodule.input_size}
  is_train: true

val_test_transform:
  _target_: src.court.arguments.prepare_transform.prepare_transform
  input_size: ${litdatamodule.input_size}
  is_train: false 