model:
  path: 'checkpoints\court\fpn\court-epoch=00-val_loss=0.0042.ckpt'

input_video: "data/test/video_input2.mp4"
output_video: "outputs/court/overlay_fpn.mp4"

input_size: [360, 640]
num_keypoints: 1

# NMS 周りの閾値など
threshold: 0.5
min_distance: 10
radius: 5
kp_color: [0, 255, 0]

batch_size: 1
device: "cpu"
