# Object Detection 用のプロセッサ＆モデル設定
processor:
  _target_: transformers.AutoImageProcessor.from_pretrained
  pretrained_model_name_or_path: "PekingU/rtdetr_v2_r18vd"

model:
  _target_: transformers.RTDetrV2ForObjectDetection.from_pretrained
  pretrained_model_name_or_path: "PekingU/rtdetr_v2_r18vd"
  num_labels: 1
  ignore_mismatched_sizes: True

# 学習済み checkpoint
model_checkpoint: "checkpoints/player/rt_detr_tracking/best-epoch=05-val_loss_total=2.2782.ckpt"

input_video: "data/test/video_input2.mp4"
output_video: "outputs/player_video.mp4"

device: "cpu"
batch_size: 8
threshold: 0.6

# ラベルマップ (ID → クラス名)
label_map:
  0: "player"
