# @package _global_.model

# RT-DETR モデル設定
net:
  _target_: transformers.RTDetrForObjectDetection.from_pretrained

  # モデルパラメータ
  pretrained_model_name_or_path: "PekingU/rtdetr_v2_r18vd"
  num_labels: 1  # プレーヤーのみ

# メタ情報をまとめる
meta:
  name: rtdetr
  output_type: "detection" 