# コールバック設定
checkpoint:
  _target_: pytorch_lightning.callbacks.ModelCheckpoint
  dirpath: "runs/${version}/checkpoints"
  filename: "{epoch:03d}-{val_loss:.8f}"
  monitor: "val_loss"
  mode: "max"
  save_top_k: 3
  save_last: true

early_stopping:
  _target_: pytorch_lightning.callbacks.EarlyStopping
  monitor: "val_loss"
  patience: 10
  mode: "max"
  verbose: true

lr_monitor:
  _target_: pytorch_lightning.callbacks.LearningRateMonitor
  logging_interval: "epoch" 