# Self-Training特有の設定
confidence_threshold: 0.7  # 擬似ラベルとして採用する信頼度の閾値
max_cycles: 3  # 最大自己学習サイクル数
pseudo_label_weight: 0.5  # 擬似ラベルの重み付け係数

# 軌跡追跡設定
use_trajectory_tracking: true  # 軌跡追跡を使用するか
trajectory_params:
  temporal_window: 9  # 軌跡推定に使用する時間ウィンドウのサイズ
  max_trajectory_gap: 5  # 補間可能な最大フレームギャップ
  min_trajectory_length: 7  # 有効な軌跡とみなす最小長
  interpolation_method: "quadratic"  # 補間方法
  smoothing_window: 5  # 平滑化ウィンドウサイズ
  max_ball_speed: 100.0  # 最大ボール速度（ピクセル/フレーム）

# 早期終了設定
min_pseudo_labels: 10  # 最小擬似ラベル数（これ以下なら終了）

# 保存設定
save_dir: "outputs/ball/self_training/${version}" 