# コールバック設定
model_checkpoint:
  _target_: pytorch_lightning.callbacks.ModelCheckpoint
  dirpath: "models/checkpoints/player"
  filename: "best-{epoch:02d}-{val_loss_total:.6f}"
  monitor: "val_loss_total"
  mode: "min"
  save_top_k: 3
  save_last: true
  verbose: true

early_stopping:
  _target_: pytorch_lightning.callbacks.EarlyStopping
  monitor: "val_loss_total"
  patience: 10
  mode: "min"
  verbose: true

lr_monitor:
  _target_: pytorch_lightning.callbacks.LearningRateMonitor
  logging_interval: "epoch" 