# Self-Training用ボール検出データモジュール設定
_target_: src.ball.lit_datamodule.self_training_data_module.SelfTrainingBallDataModule

# データパス
labeled_annotation_file: 'datasets/ball/annotations/ball_annotations.json'
unlabeled_annotation_file: 'datasets/ball/annotations/unlabeled_annotations.json'
image_root: 'datasets/ball/images'

# 入力設定
T: 3
batch_size: 16  # self-trainingでは小さめのバッチサイズ
num_workers: 4
skip_frames_range: [1, 5]
input_type: "cat"
output_type: "last"
dataset_type: "heatmap"  # "heatmap" or "coord"

# 画像サイズ設定
input_size: [360, 640]
heatmap_size: [360, 640]

# 擬似ラベル設定
use_pseudo_labels: true
pseudo_label_path: null  # 動的に設定される

# 変換設定
train_transform:
  _target_: src.ball.arguments.prepare_transform.prepare_transform
  input_size: ${litdatamodule.input_size}
  is_train: true

val_test_transform:
  _target_: src.ball.arguments.prepare_transform.prepare_transform
  input_size: ${litdatamodule.input_size}
  is_train: false 