# Transformerモデル設定
net:
  _target_: src.event.models.transformer.EventTransformer

  # モデル構成パラメータ
  d_model: 256
  nhead: 8
  num_encoder_layers: 3
  num_decoder_layers: 3
  dim_feedforward: 1024
  dropout: 0.1
  pos_encoding_type: "learnable"
  
  # バックボーン関連のパラメータはDataModuleから自動取得されます

# メタ情報をまとめる
meta:
  name: transformer
  output_type: "sequence" 