# コールバック設定
checkpoint:
  _target_: pytorch_lightning.callbacks.ModelCheckpoint
  dirpath: null
  filename: "{epoch:03d}-{val_loss:.8f}"
  monitor: "val_loss"
  mode: "min"
  save_top_k: 3
  save_last: true

early_stopping:
  _target_: pytorch_lightning.callbacks.EarlyStopping
  monitor: "val_loss"
  patience: 3  # より短いpatience
  mode: "min"
  verbose: true
  min_delta: 0.001  # 最小改善量を設定
  strict: true  # より厳格な判定

lr_monitor:
  _target_: pytorch_lightning.callbacks.LearningRateMonitor
  logging_interval: "epoch" 