# configs/infers/auto_court.yaml
coco_json:      data/ball/coco_annotations_ball_pose.json
image_root:     data/ball/images
output_json:    data/ball/coco_annotations_ball_pose_court.json

model:
  path:         checkpoints/court/fpn/court-epoch=00-val_loss=0.0042.ckpt
device:         cpu
input_size:     [256, 256]
threshold:      0.5
min_distance:   10
batch_size:     8
