lr: 0.001
weight_decay: 0.0001
warmup_epochs: 1
max_epochs: 50
bce_weight: 0.7
annotation_file: datasets/ball/coco_annotations_ball_pose_court.json
image_root: datasets/ball/images
T: 3
batch_size: 32
num_workers: 8
input_size:
- 360
- 640
heatmap_size:
- 360
- 640
skip_frames_range:
- 1
- 5
input_type: cat
output_type: last
dataset_type: coord
