# JSON 入出力
json_in:   'data\ball\coco_annotations_ball_ranged.json'
json_out:  'data\ball\coco_annotations_ball_pose.json'
img_root:  'data\ball\images'

# デバイス／バッチサイズ
device:       "cuda"
batch_size:   32
num_workers:  8     # ← 追加：DataLoader のワーカー数

# ── Player（DETR）検出モデル設定 ─────────────────────────
det_processor:
  _target_: transformers.AutoImageProcessor.from_pretrained
  pretrained_model_name_or_path: "PekingU/rtdetr_v2_r18vd"

det_model:
  _target_: transformers.RTDetrV2ForObjectDetection.from_pretrained
  pretrained_model_name_or_path: "PekingU/rtdetr_v2_r18vd"
  num_labels: 1
  ignore_mismatched_sizes: True

det_checkpoint: "checkpoints/player/rt_detr_tracking/best-epoch=05-val_loss_total=2.2782.ckpt"
player_label_id: 0
det_score_thresh: 0.6

# ── 姿勢推定モデル設定 ───────────────────────────────
pose_processor:
  _target_: transformers.AutoProcessor.from_pretrained
  pretrained_model_name_or_path: "usyd-community/vitpose-base-simple"

pose_model:
  _target_: transformers.VitPoseForPoseEstimation.from_pretrained
  pretrained_model_name_or_path: "usyd-community/vitpose-base-simple"

pose_score_thresh: 0.6
