model:
  lr: 1e-4
  lr_backbone: 1e-5
  weight_decay: 1e-4
  optim_t_max: 50
  min_lr: 1e-6
  num_freeze_epoch: 3
  num_labels: 1  # プレーヤーのみ
  model_name: "PekingU/rtdetr_v2_r18vd"

data:
  img_folder: "data/ball/images"
  annotation_file: "data/ball/coco_annotations_ball_ranged.json"
  cat_id_map: {2: 0}
  use_original_path: true
  batch_size: 4
  num_workers: 4

trainer:
  max_epochs: 10
  precision: "16-mixed"
  devices: 1
  accelerator: "gpu"
  log_every_n_steps: 10
  checkpoint_path: null

checkpoint:
  monitor: "val_loss_total"
  mode: "min"
  save_top_k: 3
  filename: "best-{epoch:02d}-{val_loss_total:.4f}"
  save_last: true